##
##  Makefile -- Build procedure for sample mime_static_html Apache module
##  Autogenerated via ``apxs -n mime_static_html -g''.
##

builddir=.
top_srcdir=/usr/local/apache2/
top_builddir=/usr/local/apache2/
include /usr/local/apache2//build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules

#   cleanup
clean:
	-rm -f mod_mime_static_html.o mod_mime_static_html.lo mod_mime_static_html.slo mod_mime_static_html.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/mime_static_html

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

tidy:
	indent -i4 -npsl -di0 -br -nce -d0 -cli0 -npcs -nfc1 -nut mod_mime_static_html.c
